version: '2'
services:
  api:
    build: .
    ports:
     - "3222:3222"
    volumes:
     - .:/usr/src/app
    depends_on:
     - mongo
  mongo:
    image: mongo:latest
    ports:
     - "32768:27017"
